* <a href="#09:37.49" id="09:37.49">09:37.49 (EST)</a> - __[rouilj](https://github.com/rouilj)__: lmsteffan, I only see two calls to decodestring one in roundup_server.py and one in roundup_xmlrpc_server.py. The xmlrpc one is depricated. demo.py uses roundup_server.py so that explains that.
* <a href="#09:38.41" id="09:38.41">09:38.41 (EST)</a> - __[rouilj](https://github.com/rouilj)__: How did you install? pypi, tarball from sourceforge? I assume you grabbed the tarball?
* <a href="#09:48.16" id="09:48.16">09:48.16 (EST)</a> - __[lmsteffan](https://github.com/lmsteffan)__: 1
* <a href="#09:54.44" id="09:54.44">09:54.44 (EST)</a> - __[rouilj](https://github.com/rouilj)__: lmsteffan, I responded to you above youc an chekc the log for my response. but the decodestring issue should be fixed on tip in bc2b00afa980. Thanks for raising the issue.
* <a href="#09:55.29" id="09:55.29">09:55.29 (EST)</a> - __[rouilj](https://github.com/rouilj)__: the two scripts affected are not included in the test suuite, so our 3.9 ci instance didn't flag it.
* <a href="#09:57.19" id="09:57.19">09:57.19 (EST)</a> - __[rouilj](https://github.com/rouilj)__: howver I have no other errors in our 3.9 ci chain, so I am not sue what your are seeing. Where is the assertion error? Also the StopIteration errors should be geting trapped by python
* <a href="#09:57.23" id="09:57.23">09:57.23 (EST)</a> - __[rouilj](https://github.com/rouilj)__: and not exposed.
* <a href="#09:57.55" id="09:57.55">09:57.55 (EST)</a> - __[rouilj](https://github.com/rouilj)__: that's a normal exception generated at end of loop/generator.
* <a href="#09:59.43" id="09:59.43">09:59.43 (EST)</a> - __[rouilj](https://github.com/rouilj)__: you can see our 3.9 run (called 3.9-dev) of run_tests.py at: https://travis-ci.org/github/roundup-tracker/roundup/builds/746624845
* <a href="#10:05.52" id="10:05.52">10:05.52 (EST)</a> - __[rouilj](https://github.com/rouilj)__: also lmsteffan what is the source of your roundup code? Tarball, hg or git clone, pypi?
* <a href="#10:06.39" id="10:06.39">10:06.39 (EST)</a> - __[lmsteffan](https://github.com/lmsteffan)__: I got it using "hg clone" (after using pypi and seeing some errors)
* <a href="#10:08.03" id="10:08.03">10:08.03 (EST)</a> - __[lmsteffan](https://github.com/lmsteffan)__: I did not see your initial response, I'll check it in the log as soon as it's available.
* <a href="#11:05.40" id="11:05.40">11:05.40 (EST)</a> - __[rouilj](https://github.com/rouilj)__: it should be in the log. lmc
* <a href="#11:07.02" id="11:07.02">11:07.02 (EST)</a> - __[rouilj](https://github.com/rouilj)__: yup in the log, but you answered my questions.
* <a href="#11:08.03" id="11:08.03">11:08.03 (EST)</a> - __[rouilj](https://github.com/rouilj)__: can you provide some more info on the untrapped exception errors (line numbers, exact error messages, failing test info....)
* <a href="#12:02.04" id="12:02.04">12:02.04 (EST)</a> - __[lmsteffan](https://github.com/lmsteffan)__: sure ! do I copy it here (on IRC) or should I create a new issue or ... ?
* <a href="#13:20.02" id="13:20.02">13:20.02 (EST)</a> - __[lmsteffan](https://github.com/lmsteffan)__: I should mention that all the assertion errors are related to pytest, not to roundup directly. I suspect that these errors are related to PEP 479 which introduced some changes for generators.
* <a href="#13:21.09" id="13:21.09">13:21.09 (EST)</a> - __[lmsteffan](https://github.com/lmsteffan)__: see https://docs.python.org/3.5/whatsnew/3.5.html#pep-479-change-stopiteration-handling-inside-generators
* <a href="#17:20.49" id="17:20.49">17:20.49 (EST)</a> - __[rouilj](https://github.com/rouilj)__: lsteffan, sorry for the delay. Can you try pip installing pytest and running pytest directly rather than using run_tests.py.
* <a href="#17:22.23" id="17:22.23">17:22.23 (EST)</a> - __[rouilj](https://github.com/rouilj)__: run_tests.py is an old version of pytest. It is the last version to provide a way to bundle pytest into a standalone python file so you can supply the test runner as part of your app.
* <a href="#17:23.11" id="17:23.11">17:23.11 (EST)</a> - __[rouilj](https://github.com/rouilj)__: It may be time to give up on having the distribution being testable without having to pip install pytest.
* <a href="#17:29.50" id="17:29.50">17:29.50 (EST)</a> - __[rouilj](https://github.com/rouilj)__: I think the reason everything passes in CI is that CI runs: py.test directly not the one bundled in the distribution. That is probably a newer py.test installed at test time with pip.
* <a href="#17:31.52" id="17:31.52">17:31.52 (EST)</a> - __[lmsteffan](https://github.com/lmsteffan)__: Actually I did that - running pytest on the test directory - and it went mostly all right.
* <a href="#17:32.57" id="17:32.57">17:32.57 (EST)</a> - __[lmsteffan](https://github.com/lmsteffan)__: One error does occur when pytz is not installed:
* <a href="#17:33.48" id="17:33.48">17:33.48 (EST)</a> - __[lmsteffan](https://github.com/lmsteffan)__: E           AssertionError: OptionValueError not raised by set
* <a href="#17:33.51" id="17:33.51">17:33.51 (EST)</a> - __[lmsteffan](https://github.com/lmsteffan)__: test/test_config.py:117: AssertionError
* <a href="#17:34.42" id="17:34.42">17:34.42 (EST)</a> - __[lmsteffan](https://github.com/lmsteffan)__: and disappears when pytz is installed.
* <a href="#17:37.07" id="17:37.07">17:37.07 (EST)</a> - __[lmsteffan](https://github.com/lmsteffan)__: For what it's worth, I think that (at least on Linux) it's so easy to install pytest and run the tests that I don't ses much added value in having a bundled test runner. Besides, it seems to be brittle with respect to Python version changes, doesn't it ?
